<?php return array (
  'navbar_inverse' => 'true',
  'homeTabVisable' => 'true',
  'musicTabVisable' => 'true',
  'visualsTabVisable' => 'true',
  'teamTabVisable' => 'true',
  'blogTabVisable' => 'true',
  'brandTabText' => 'asdfhkj',
  'homeTabText' => 'asdfghi',
  'musicTabText' => 'fdsa',
  'visualsTabText' => 'fdsasdf',
  'teamTabText' => 'teamfdsa',
  'blogTabText' => 'blog',
  'adminTabText' => 'Admin',
  'logoutTabText' => 'Logout',
  'indexTitle' => '"CUHLT"',
  'blogTitle' => '"CUHLT BLOG"',
  'mediaSoundsTitle' => '"CUHLT MUSIC"',
  'mediaVisualsTitle' => '"CUHLT VISUALS"',
  'teamTitle' => '"CUHLT MEMBERS"',
  'adminLoginTitle' => '"ADMIN LOGIN"',
  'adminMainTitle' => '"Admin Main Page"',
  'nav_inverse' => 'true',
);